### ISSUE TITLE
Dark Mode Cinflict using Mary UI

### ISSUE THREAD

**Issue by mai1237** [thedevdojo/genesis#27]
This is the Dark mode i got with Mary UI components
![image](https://github.com/thedevdojo/genesis/assets/2780148/8adaebe9-bda1-409d-9533-368bb9473286)

**Comment by tnylea** [comment]
Can you share with me the steps with how I can install this library and get the same results that you have. Thanks.

**Comment by mai1237** [comment]
npm i -D  daisyui@latest postcss autoprefixer
composer require robsontenorio/mary
in the file tailwind.config.js
i added
    content: [
			...
        // Add mary
        "./vendor/robsontenorio/mary/src/View/Components/**/*.php",
    ],

    plugins: [
				...
                // Add daisyUI
                require("daisyui"),
    ],
then i run
npm run build

**Comment by tnylea** [comment]
Hey @mai1237,

I just tried using Genesis with Mary and it looks like it's causing a conflict with the main layout or possibly some of the components. Here's a screenshot of the updated dashboard.

<img width="1722" alt="CleanShot 2023-09-12 at 10 01 04@2x" src="https://github.com/thedevdojo/genesis/assets/601261/adb5af38-1a50-45b0-abfe-a86a9148abbb">

It also seems that the dark mode switch is no longer working (probably because the main layout file gets overwritten with an install). Is there a reason that you want to use MaryUI with Genesis? Let me know. Perhaps It's something I could build into Genesis.

As for now, it looks like MaryUI is not compatible with the latest version of Genesis, so I wouldn't really be able to help debug. If there are any PR's you want to submit that would make it compatible, let me know. I'm flexible to make some changes to make it compatible with other libraries :)

Thanks!
